# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2019-02-23 09:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='creat_time',
            new_name='created_time',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='modify_time',
            new_name='modified_time',
        ),
    ]
